In [6]:
import numpy as np

### Numpy Data-type

In [39]:
a = np.array([1,5,9], dtype = np.int32)

In [40]:
print(a)

[1 5 9]


In [41]:
a.dtype

dtype('int32')

In [34]:
c = np.array([True, False, True], dtype = bool)

In [35]:
c.dtype

dtype('bool')

In [36]:
c

array([ True, False,  True])

In [30]:
c = np.array(["Ram", "shaym", "hari"])

In [27]:
c

array(['Ram', 'shaym', 'hari'], dtype='<U5')

In [28]:
c.dtype

dtype('<U5')

### Type Conversion

In [37]:
c

array([ True, False,  True])

In [38]:
c.astype(np.float64)

array([1., 0., 1.])

In [43]:
a.astype(np.float32)

array([1., 5., 9.], dtype=float32)