In [1]:
import numpy as np

In [2]:
a = np.array([1,4,6,9,0,3,5,2])

In [3]:
a

array([1, 4, 6, 9, 0, 3, 5, 2])

In [5]:
mask = a > 5

In [8]:
a[mask]

array([6, 9])

In [10]:
a_2d = np.array([[1,4],[6,9],[0,3],[5,2]])

In [12]:
a_2d, a_2d.shape

(array([[1, 4],
        [6, 9],
        [0, 3],
        [5, 2]]),
 (4, 2))

In [24]:
mask_a = np.array([True, False, True, True])

In [25]:
a_2d[mask_a]

array([[1, 4],
       [0, 3],
       [5, 2]])

In [27]:
a_2d[a_2d > 2]

array([4, 6, 9, 3, 5])