In [1]:
import numpy as np

## Elementwise Operations

Refer to : https://numpy.org/doc/1.26/reference/array_api.html#elementwise-functions

In [13]:
a = np.array([[4, 5, 6], [5, 7, 9]])
b = np.array([[1, 2, 3], [9, 8,7 ]])

In [14]:
print(a)
print("-"*20)
print(b)

[[4 5 6]
 [5 7 9]]
--------------------
[[1 2 3]
 [9 8 7]]


In [15]:
a + b

array([[ 5,  7,  9],
       [14, 15, 16]])

In [9]:
b - a

array([[-3, -3, -3],
       [ 4,  1, -2]])

## Matrix Operations
Refer to : https://numpy.org/doc/1.26/reference/routines.linalg.html

In [27]:
a = np.array([[8, 5, 6, 7], [5, 73, 7,8]])
b = np.array([[1, 2, 7,8], [97,8,8, 8], [1, 2, 7,8], [97,8,8, 8]])

In [28]:
print(a)
print("-"*20)
print(b)

[[ 8  5  6  7]
 [ 5 73  7  8]]
--------------------
[[ 1  2  7  8]
 [97  8  8  8]
 [ 1  2  7  8]
 [97  8  8  8]]


In [29]:
np.dot(a,b)

array([[1178,  124,  194,  208],
       [7869,  672,  732,  744]])

In [30]:
np.transpose(a)

array([[ 8,  5],
       [ 5, 73],
       [ 6,  7],
       [ 7,  8]])

In [35]:
np.trace(b, offset=-1)

107

In [37]:
a_22 = np.array([[8, 5], [5, 7]])

np.linalg.det(a_22)

31.0

In [44]:
d = np.random.randint(0,50,(2, 3))

In [46]:
np.linalg.det(d)

LinAlgError: Last 2 dimensions of the array must be square

In [55]:
# Mathematical Inverse

a_22 = np.array([[8, 5], [5, 7]])
a_22_adj = np.array([[7, -5], [-5, 8]])


In [56]:
a_22_inv = (1/ np.linalg.det(a_22)) * a_22_adj

In [57]:
a_22_inv

array([[ 0.22580645, -0.16129032],
       [-0.16129032,  0.25806452]])

In [58]:
np.linalg.inv(a_22)

array([[ 0.22580645, -0.16129032],
       [-0.16129032,  0.25806452]])

In [63]:
# https://numpy.org/doc/1.26/reference/generated/numpy.linalg.eig.html
np.linalg.eig(a_22)

EigResult(eigenvalues=array([12.52493781,  2.47506219]), eigenvectors=array([[ 0.74145253, -0.67100532],
       [ 0.67100532,  0.74145253]]))

In [64]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)

In [65]:
x

array([-1.,  1.])

## Numpy Broadcasting

In [17]:
a = np.array([[1, 2], [3, 5]])
b = np.array([10, 20])

In [18]:
a , a.shape

(array([[1, 2],
        [3, 5]]),
 (2, 2))

In [19]:
b, b.shape

(array([10, 20]), (2,))

In [20]:
a + b

array([[11, 22],
       [13, 25]])

### Why numpy over Python's loop ?

In [7]:
import numpy as np
import time

In [8]:
# NumPy element_wise operation
a = np.random.rand(5000000)
b = np.random.rand(5000000)

start = time.time()
c = a * b
end_time = time.time()

numpy_execution_time = end_time - start


In [9]:
# Python Execution
a_list = list(a)
b_list = list(b)
c_list = []

start = time.time()
for i in range(len(a_list)):
    c_list.append(
        a_list[i] * b_list[i]
    )
end = time.time()

python_execution_time = end -start


In [10]:
numpy_execution_time

0.008596658706665039

In [11]:
python_execution_time

0.4402141571044922

In [12]:
print(f"Numpy is {python_execution_time/numpy_execution_time} times faster")

Numpy is 51.20758798568932 times faster
