In [26]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
data = pd.read_csv("clean_data.csv")
data.head()

year  month stateDescription   sectorName  customers  price   revenue  \
0  2001      1          Wyoming  all sectors        NaN   4.31  48.12840   
1  2001      1          Wyoming   commercial        NaN   5.13  12.67978   
2  2001      1          Wyoming   industrial        NaN   3.26  19.60858   
3  2001      1          Wyoming        other        NaN   4.75   0.76868   
4  2001      1          Wyoming  residential        NaN   6.01  15.07136   

        sales  
0  1116.17208  
1   247.08691  
2   602.30484  
3    16.17442  
4   250.60591

## Label Encoding

- Ordinal Data

In [4]:
X = data['sectorName']

In [9]:
# pandas way
encoded, rule = X.factorize()

In [11]:
encoded

array([0, 1, 2, ..., 2, 4, 5])

In [12]:
rule

Index(['all sectors', 'commercial', 'industrial', 'other', 'residential',
       'transportation'],
      dtype='object')

In [16]:
# sklearn way
lEncoder  = LabelEncoder()

encoded = lEncoder.fit_transform(X)
encoded

array([0, 1, 2, ..., 2, 4, 5])

In [18]:
lEncoder.inverse_transform([0,4,3,2])

array(['all sectors', 'residential', 'other', 'industrial'], dtype=object)

## One-Hot Encoding

- Nomial Data

In [24]:
# pandas
pd.get_dummies(X, dtype=int)

all sectors  commercial  industrial  other  residential  transportation
0                1           0           0      0            0               0
1                0           1           0      0            0               0
2                0           0           1      0            0               0
3                0           0           0      1            0               0
4                0           0           0      0            1               0
...            ...         ...         ...    ...          ...             ...
85865            1           0           0      0            0               0
85866            0           1           0      0            0               0
85867            0           0           1      0            0               0
85868            0           0           0      0            1               0
85869            0           0           0      0            0               1

[85870 rows x 6 columns]

In [31]:
# sklearn
one_hot_encoder = OneHotEncoder(sparse_output=False)

encoder = one_hot_encoder.fit_transform(X.values.reshape(-1,1))

In [32]:
encoder

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
one_hot_encoder.categories_

[array(['all sectors', 'commercial', 'industrial', 'other', 'residential',
        'transportation'], dtype=object)]

In [39]:
one_hot_encoder

OneHotEncoder(sparse_output=False)