1D Array: `array_name[idx]` (Similar to Python list)

2D Array: `array_name[row_idx, col_idx]` (Similar to Matrix)

ND Array: `array_name[dim1_idx, dim2_idx, ..., dimN_idx]`

## Indexing Numpy Array

### One Dimension

In [8]:
list1 = [23,-7,9,6, 4]
print(list1)

[23, -7, 9, 6, 4]


In [4]:
list1[4]

4

In [5]:
import numpy as np 

In [7]:
array1 = np.array(list1)
print(array1)

[23 -7  9  6  4]


In [9]:
array1[4]

4

### Multi Dimension

In [12]:
# 2D Array > Similar to Matrix

list2 = [[2,5,7,],[4, 9,11]]
array2 = np.array(list2)

In [13]:
print(array2)

[[ 2  5  7]
 [ 4  9 11]]


In [16]:
array2.shape

(2, 3)

In [19]:
array2[1][2]

11

In [20]:
array2[1, 2]

11

In [21]:
# ND 
random_array = np.random.randint(low = 10, high = 50, size = (2,3,4))
print(random_array)

[[[16 12 49 10]
  [45 19 44 42]
  [32 37 25 32]]

 [[42 23 48 18]
  [20 39 28 40]
  [29 39 17 34]]]


In [22]:
random_array.ndim

3

In [23]:
random_array.shape

(2, 3, 4)

In [28]:
random_array[0, 2, 2] # similar to random_array[0][2][2]

25

In [42]:
random_array = np.random.randint(low = 10, high = 50, size = (10,2,2))
print(random_array)

[[[17 31]
  [36 13]]

 [[37 44]
  [14 27]]

 [[30 34]
  [33 11]]

 [[29 49]
  [44 39]]

 [[15 12]
  [15 30]]

 [[11 38]
  [47 26]]

 [[33 20]
  [44 36]]

 [[11 18]
  [33 11]]

 [[40 40]
  [32 27]]

 [[18 33]
  [38 25]]]


In [43]:
random_array.shape

(10, 2, 2)

In [46]:
random_array[-1, -2, 1]

33

## Slicing Numpy array

### 1D

In [59]:
list2 = [4,7,0,45,67,8, 66.2]

In [60]:
list2[:-1] #list2[start index : stop index : step ]

[4, 7, 0, 45, 67, 8]

In [61]:
slice_array = np.array(list2)
print(slice_array)

[ 4.   7.   0.  45.  67.   8.  66.2]


In [63]:
slice_array[ :-2 : 2]

array([ 4.,  0., 67.])

### 2D

In [64]:
list2d = [[1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5, 7, 9, 11, 13, 15]]
slice2d_array = np.array(list2d)
print(slice2d_array)

[[ 1  2  3  4  5  6  7  8]
 [ 1  3  5  7  9 11 13 15]]


In [65]:
slice2d_array.shape

(2, 8)

In [71]:
slice2d_array[0, 2:]

array([3, 4, 5, 6, 7, 8])

In [72]:
list2d = [[1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5, 7, 9, 11, 13, 15], [15, 25, 9999, 376, 19, 420, 786, 555]]
slice2d_array = np.array(list2d)
print(slice2d_array)

[[   1    2    3    4    5    6    7    8]
 [   1    3    5    7    9   11   13   15]
 [  15   25 9999  376   19  420  786  555]]


In [73]:
slice2d_array.shape

(3, 8)

In [79]:
slice2d_array[1:,4:7]

array([[  9,  11,  13],
       [ 19, 420, 786]])

### 3D

In [81]:
random_array = np.random.randint(low = 10, high = 50, size = (4,3,4))
print(random_array)

[[[38 41 49 14]
  [32 38 39 17]
  [35 11 28 19]]

 [[16 42 25 36]
  [23 10 45 35]
  [17 19 12 17]]

 [[43 10 13 20]
  [11 14 21 25]
  [27 47 15 20]]

 [[23 34 36 37]
  [20 16 26 35]
  [18 41 20 23]]]


In [92]:
random_array[-2:,:2,:2]

array([[[43, 10],
        [11, 14]],

       [[23, 34],
        [20, 16]]])

In [102]:
random_array[-2:,:2,::2]

array([[[43, 13],
        [11, 21]],

       [[23, 36],
        [20, 26]]])

### ND

In [104]:
random_array = np.random.randint(low = 10, high = 50, size = (3,2,4,3))
print(random_array)

[[[[27 15 13]
   [14 23 43]
   [19 38 12]
   [24 49 19]]

  [[41 44 39]
   [46 14 29]
   [30 48 10]
   [25 14 29]]]


 [[[40 43 44]
   [24 44 46]
   [18 12 46]
   [34 18 40]]

  [[11 49 31]
   [10 18 26]
   [41 27 22]
   [40 20 23]]]


 [[[43 12 32]
   [21 31 24]
   [43 40 25]
   [48 27 19]]

  [[18 33 33]
   [32 13 21]
   [10 24 11]
   [42 31 40]]]]


In [110]:
random_array[:2,:2,:2,:2]

array([[[[27, 15],
         [14, 23]],

        [[41, 44],
         [46, 14]]],


       [[[40, 43],
         [24, 44]],

        [[11, 49],
         [10, 18]]]])