In [1]:
import numpy as np

In [66]:
random_array = np.random.randint(low = 10, high = 50, size = (3,6))
random_array1 = np.random.randint(low = 10, high = 50, size = (4,6))
print(random_array)
print()
print(random_array1)

[[10 18 24 36 47 29]
 [40 47 10 43 46 41]
 [49 32 32 40 33 49]]

[[34 28 13 35 29 16]
 [19 26 24 16 41 35]
 [11 17 44 39 40 49]
 [16 36 40 29 11 10]]


## Attributes

In [3]:
random_array.shape

(2, 3, 2)

In [4]:
random_array.dtype

dtype('int64')

In [5]:
random_array.ndim

3

In [7]:
random_array.size

12

In [9]:
random_array.T

array([[36, 39, 43],
       [45, 43, 20]])

## Array Methods / Operations

In [12]:
random_array.sum(axis = 1)

array([81, 82, 63])

In [16]:
random_array.max(axis = 1)

array([40, 41, 28])

In [22]:
random_array.argmax(axis =1)

array([4, 4, 5])

In [27]:
random_array.flatten()

array([28, 10, 47, 28, 16, 30, 10, 31, 20, 37, 41, 38, 21, 32, 42, 47, 16,
       36, 22, 32, 14, 46, 28, 21, 47, 23, 47, 42, 47, 14, 22, 35, 46, 47,
       30, 14])

In [35]:
random_array.shape

(3, 6)

In [33]:
print(random_array)

[[21 37 13 10 43 43]
 [16 48 35 43 14 46]
 [49 44 22 26 10 15]]


In [32]:
random_array.reshape((2,9))

array([[21, 37, 13, 10, 43, 43, 16, 48, 35],
       [43, 14, 46, 49, 44, 22, 26, 10, 15]])

In [36]:
random_array.reshape((2,3,3))

array([[[21, 37, 13],
        [10, 43, 43],
        [16, 48, 35]],

       [[43, 14, 46],
        [49, 44, 22],
        [26, 10, 15]]])

In [49]:
# Concatenate
m = np.array([[1, 2], [3, 4]])
n = np.array([[5, 6], [7, 8]])

print(m)
print("="*20)
print(n)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [50]:
np.concatenate((m,n), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
string = 'hello how are you'

In [52]:
string.split(" ")

['hello', 'how', 'are', 'you']

In [67]:
random_array = random_array.flatten()

In [68]:
random_array

array([10, 18, 24, 36, 47, 29, 40, 47, 10, 43, 46, 41, 49, 32, 32, 40, 33,
       49])

In [71]:
np.split(random_array,9)

[array([10, 18]),
 array([24, 36]),
 array([47, 29]),
 array([40, 47]),
 array([10, 43]),
 array([46, 41]),
 array([49, 32]),
 array([32, 40]),
 array([33, 49])]

In [75]:
np.split(random_array, [2,3,10, 12])

[array([10, 18]),
 array([24]),
 array([36, 47, 29, 40, 47, 10, 43]),
 array([46, 41]),
 array([49, 32, 32, 40, 33, 49])]