In [1]:
!pip install numpy

In [2]:
import numpy as np

## Creating Numpy array

In [16]:
# np.array()

# 1D
list1 = [11,2,4]

array1 = np.array(list1)

print(array1)
print(type(array1))
print(array1.ndim)

[11  2  4]
<class 'numpy.ndarray'>
1


In [20]:
# np.array()

# 2D

list2 = [
            [ 1,4,6 ],
            [ 7,8,2 ]
        ]

array2 = np.array(list2)

print(array2)
print(type(array2))
print(array2.ndim)

[[1 4 6]
 [7 8 2]]
<class 'numpy.ndarray'>
2


In [25]:
# np.zeros() 
# 1D

array_zero = np.zeros(5)
print(array_zero)

[0. 0. 0. 0. 0.]


In [26]:
# np.zeros() 

array_zero = np.zeros((2,3))
print(array_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# np.ones()
# 1D
array_ones = np.ones(5)
print(array_ones)

[1. 1. 1. 1. 1.]


In [28]:
# np.ones()
# 1D
array_ones = np.ones((2,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# np.full()
# 1D
array_full = np.full(shape = 5, fill_value = 3.2 )
print(array_full)

print(array_full.dtype)

[3.2 3.2 3.2 3.2 3.2]
float64


In [40]:
# np.full()

array_full = np.full(shape = (2,3), fill_value = 5 )
print(array_full)

print(array_full.dtype)

print(array_full.shape)

[[5 5 5]
 [5 5 5]]
int64
(2, 3)


In [42]:
# range(<start>, <end>, <step>)
list(range(1,10, 2))

[1, 3, 5, 7, 9]

In [44]:
# np.arange(start, stop, step)
# Can only define array of 1D

array_range1 = np.arange(1,10)
print(array_range1)

[1 2 3 4 5 6 7 8 9]


In [45]:
array_range1 = np.arange(-6.3,13.6, 2.67)
print(array_range1)

[-6.3  -3.63 -0.96  1.71  4.38  7.05  9.72 12.39]


In [49]:
# np.linspace(start, stop, element) > linear space

array_linspace1 = np.linspace(start=0, stop=10, num=5)
print(array_linspace1)

[ 0.   2.5  5.   7.5 10. ]


In [57]:
array_linspace2 = np.linspace(start= (0,0,0), stop= (10,20,30), num=5, axis =1)
print(array_linspace2)

[[ 0.   2.5  5.   7.5 10. ]
 [ 0.   5.  10.  15.  20. ]
 [ 0.   7.5 15.  22.5 30. ]]


In [58]:
# np.diag() > Square matrix

diag_array1= np.diag([1,2,3])
print(diag_array1)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [63]:
diag_array1= np.diag([4,5,6,7], k =-1)
print(diag_array1)

print(diag_array1.dtype)

[[0 0 0 0 0]
 [4 0 0 0 0]
 [0 5 0 0 0]
 [0 0 6 0 0]
 [0 0 0 7 0]]
int64


In [72]:
# np.eye() diagonal matix with 1
eye_array1 = np.eye(N = 5, M=4)
print(eye_array1)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [73]:
# np.identity()
# diagonal matrix with 1  > identity matrix
# less used in industry
identity_array = np.identity(5)
print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [88]:
# np.random
random_array = np.random.rand(1,2,5)
print(random_array)
print(random_array.ndim)

[[[0.90503404 0.96546354 0.86516598 0.95315999 0.64554532]
  [0.10528681 0.2146232  0.87946565 0.22310857 0.94911542]]]
3


In [89]:
def dimension(*args):
    print(f"DImension of {len(args)}")
dimension(1,5,6)

DImension of 3


In [96]:
random_array = np.random.randint(low = 10, high = 50, size = (2,3,4))
print(random_array)
print(random_array.ndim)

[[[48 27 17 44]
  [43 18 13 42]
  [23 30 29 19]]

 [[39 46 43 26]
  [16 33 46 38]
  [36 32 20 42]]]
3


In [94]:
print(random_array.shape)

(2, 3, 4)
